const movies = [
  "Cool Hand Luke",
  "Primer",
  "Dirty Rotten Scoundrels",
  "Ocean's 11",
  "The Girl Who Leapt Through Time",
  "Get Out",
  "The Last Dragon",
  "OldBoy",
  "Grave of the Fireflies",
  "Eraserhead",
  "Black Swan",
  "La La Land",
  "The Truman Show",
  "Interstellar",
  "The Deer Hunter",
  "Fear and Loathing in Las Vegas",
  "Heavy Metal",
  "Dune",
  "Full Metal Jacket",
  "Grandma's Boy",
  "Good Burger",
  "Spirited Away",
  "SkinWalker Ranch",
  "Repo Man",
  "Back to the Future Part II",
  "Eternal Sunshine of the Spotless Mind",
  "Drop Dead Fred",
  "Grumpy Old Men",
  "Dan In Real Life",
  "Idiocracy"
];

module.exports = movies;
